meta:
  name: 'DKConnect English'
  module: 'DKConnect'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkconnect.prefix: '&8» &eDKConnect &8|&f'

  dkconnect.error.onlyPlayer: '${dkconnect.prefix} &cThis command can only be executed as a player'
  dkconnect.error.player.alreadyVerified: '${dkconnect.prefix} &cYou are already verified to &{verification.username}'
  dkconnect.error.player.openPendingVerification: '${dkconnect.prefix} &7You have already an open pending verification. &7Your personal verification code is &e{pendingVerification.code}. &7Execute the command &e!verify {pendingVerification.code} to the &ePretronicBot'
  dkconnect.error.player.notVerified: '${dkconnect.prefix} &cYou are not verified'
  dkconnect.error.player.notFound: '${dkconnect.prefix} &cPlayer &e{name} &cnot found'

  dkconnect.command.verify: '${dkconnect.prefix} &7Your personal verification code is &e{pendingVerification.code}. &7Execute the command &e!verify {pendingVerification.code} to the &ePretronicBot'
  dkconnect.command.unverify: '${dkconnect.prefix} &7You are now unverified'
  dkconnect.command.verifyInfo: '${dkconnect.prefix} &7Verifications for &e{player.displayName}
  @for("verification" in {player.verifications},${dkconnect.command.verifyInfo.loop},"\n")'
  dkconnect.command.verifyInfo.loop: ' &8- &e{verification.username} &8(&e{verification.userId}&8)'

  dkconnect.voiceadapter.discord.command.verifiy.usage.author.name: 'Wrong usage'
  dkconnect.voiceadapter.discord.command.verifiy.usage.author.url: 'https://www.paypal.com/pools/c/8aWrUZXUi6'
  dkconnect.voiceadapter.discord.command.verifiy.usage.author.iconUrl: 'https://i.imgur.com/yqKqqTX.png'
  dkconnect.voiceadapter.discord.command.verifiy.usage.color: 'RANDOM_BRIGHT'
  dkconnect.voiceadapter.discord.command.verifiy.usage.description: 'Test description'
  dkconnect.voiceadapter.discord.command.verifiy.usage.thumbnail: 'https://i.imgur.com/mvuOqlq.png'

  dkconnect.voiceadapter.discord.command.unverify.completed: 'You have unverified your minecraft account with the name {verification.player.name}'
  dkconnect.voiceadapter.discord.command.unverify.notVerified: 'You are not verified'
  dkconnect.voiceadapter.discord.command.verify.completed: 'You have completed your verification for the minecraft player {verification.player.name}'
  dkconnect.voiceadapter.discord.command.verify.noPendingVerification: 'There is no pending verification for {code} available'
  dkconnect.voiceadapter.discord.command.verify.usage: 'Usage: {commandPrefix}verify <code>'

  dkconnect.voiceadapter.discord.notification.ban.title: 'New {event.snapshot.punishmentType.name}'
  dkconnect.voiceadapter.discord.notification.ban.fields.banId.name: '{event.snapshot.punishmentType.name} ID'
  dkconnect.voiceadapter.discord.notification.ban.fields.staff.name: 'Staff'
  dkconnect.voiceadapter.discord.notification.ban.fields.reason.name: 'Reason'
  dkconnect.voiceadapter.discord.notification.ban.fields.duration.name: 'Duration'

  dkconnect.voiceadapter.discord.notification.join.body: '{event.player.name} has joined the server'
  dkconnect.voiceadapter.discord.notification.leave.body: '{event.player.name} has left the server'

  dkconnect.chatSync.message: '<{player.name}> {message}'
